namespace PhyrosClassroom.Households.Models;

public sealed record HouseholdReadModel(
    Guid HouseholdId,
    string HouseholdCode,
    string GivenName,
    string FamilyName,
    DateTimeOffset RegisteredAtUtc,
    string? SourceSystem,
    string? SourceReference,
    DateOnly? BirthDate,
    string? GradeLevel,
    string? PrimaryGuardianName,
    string? PrimaryGuardianEmail,
    bool HasMedicalAlert,
    string? MedicalNotes,
    bool HasIep,
    IReadOnlyList<HouseholdDocumentReference> Documents,
    IReadOnlyList<HouseholdRecordNote> Notes,
    string SubjectId = "",
    Guid? SourceRegistrationId = null,
    string? SourceRegistrationStatus = null,
    DateTimeOffset? SourceRegistrationUpdatedAtUtc = null,
    string HouseholdName = "",
    bool WantsEmailNotifications = false,
    bool WantsSmsNotifications = false,
    string? OnboardingStatus = null,
    IReadOnlyList<HouseholdContact>? Contacts = null,
    IReadOnlyList<HouseholdStudent>? Students = null,
    DateTimeOffset? UpdatedAtUtc = null);
