namespace PhyrosClassroom.Households.Models;

public sealed record HouseholdEventRecord(
    Guid HouseholdId,
    string EventType,
    DateTimeOffset OccurredUtc,
    string HouseholdCode,
    string GivenName,
    string FamilyName,
    string? SourceSystem = null,
    string? SourceReference = null,
    DateOnly? BirthDate = null,
    string? GradeLevel = null,
    string? PrimaryGuardianName = null,
    string? PrimaryGuardianEmail = null,
    bool HasMedicalAlert = false,
    string? MedicalNotes = null,
    bool HasIep = false,
    IReadOnlyList<HouseholdDocumentReference>? Documents = null,
    IReadOnlyList<HouseholdRecordNote>? Notes = null,
    string SubjectId = "",
    Guid? SourceRegistrationId = null,
    string? SourceRegistrationStatus = null,
    DateTimeOffset? SourceRegistrationUpdatedAtUtc = null,
    string HouseholdName = "",
    bool WantsEmailNotifications = false,
    bool WantsSmsNotifications = false,
    string? OnboardingStatus = null,
    IReadOnlyList<HouseholdContact>? Contacts = null,
    IReadOnlyList<HouseholdStudent>? Students = null);
